name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Project Files
        run: |
          unzip -o *.zip

      - name: Find Flutter Project Directory
        id: find_dir
        run: |
          PROJECT_DIR=$(dirname $(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1))
          echo "DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Found project directory at: $PROJECT_DIR"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd ${{ env.DIR }}
          flutter pub get

      - name: Build APK
        run: |
          cd ${{ env.DIR }}
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
